name: Scully Publish

on:
  push:
    branches:
      - base-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cmgriffing/scully-gh-pages-action@v7
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master
          build-args: "--prod"
